### ISSUE TITLE
Stop deploying unchanged images

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1019]
Deploying unchanged images is wasteful and increases the chance of failure.  Compare images and do not deploy unless different.

**Comment by mishraomp** [comment]
may be this could help https://github.com/dorny/paths-filter ,thoughts @DerekRoberts ?

**Comment by DerekRoberts** [comment]
> may be this could help https://github.com/dorny/paths-filter ,thoughts @DerekRoberts ?

Not a bad idea! We actually had this solved, but it was dropped among a pile of other changes. The biggest problem here really is time. :/

**Comment by mishraomp** [comment]
> > may be this could help https://github.com/dorny/paths-filter ,thoughts @DerekRoberts ?
> 
> Not a bad idea! We actually had this solved, but it was dropped among a pile of other changes. The biggest problem here really is time. :/

I wish I was more helpful than links :(

**Comment by DerekRoberts** [comment]
@mishraomp Ha!  You are.  You did all the contributing to this QuickStart over the last few weeks too!  :D
