### ISSUE TITLE
Pluggable Backend

### ISSUE THREAD

**Issue by conbrad** [bcgov/quickstart-openshift#1073]
**As a** *Developer/Business Area* **I want** *a choice of backend technology* **So That** *I can leverage backend ecosystem specifics for my project needs*.

I think anchoring on an opinionated stack is productive but for some projects it's useful to have a backend with dependencies that are geared towards specific purposes.

E.g being able to have a Python backend for data heavy projects is useful due to it's data wrangling/AI/ML ecosystem.

Maybe a bootstrap command that pulls in a specific tech backend for a limited number of backend options? (Python,FastAPI, Typescript,NextJS, etc.)

**Acceptance Criteria**
- [ ] Given I use `nr-quickstart-typescript`, When I bootstrap a new project, Then I can choose my backend

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by DerekRoberts** [comment]
@conbrad That would be great to pull off!  Lots of work, but enormously useful.  Hell, it could even a nodejs package instead of a template repo...  :o

**Comment by DerekRoberts** [comment]
@conbrad Done!  Thanks mostly to @mishraomp.  Repo is below, using Go, Python and Java.

https://github.com/bcgov/quickstart-openshift-backends

**Comment by conbrad** [comment]
> @conbrad Done! Thanks mostly to @mishraomp. Repo is below, using Go, Python and Java.
> 
> https://github.com/bcgov/quickstart-openshift-backends

Oh that's awesome, how would one use it in quickstart?

**Comment by DerekRoberts** [comment]
> > @conbrad Done! Thanks mostly to @mishraomp. Repo is below, using Go, Python and Java.
> > https://github.com/bcgov/quickstart-openshift-backends
> 
> Oh that's awesome, how would one use it in quickstart?

@conbrad For now it's a copy and paste, since the structures match.  I'd like to script something fancier.
