### ISSUE TITLE
Add pod distribution for our HA deployment in DC

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1074]
We need to update our DC to have better pod distribution among nodes
https://docs.openshift.com/container-platform/4.12/nodes/scheduling/nodes-scheduler-pod-topology-spread-constraints.html

**Comment by DerekRoberts** [comment]
@mishraomp Good link!  Thankfully it's handled by deployment objects, so we have nothing to do.  :)
