### ISSUE TITLE
Add integration tests with support for postgres in GHA

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1078]
Since there is support for Postgres to run as a container during the workflow, it would be nice to have integration tests for the APIs to run against it directly.
https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers

**Comment by DerekRoberts** [comment]
That's handy!  Maybe we should bake this into other places.
https://docs.github.com/en/actions/using-containerized-services/creating-postgresql-service-containers#testing-the-postgresql-service-container

**Comment by mishraomp** [comment]
this is already done @DerekRoberts :)
