### ISSUE TITLE
Add Python Backend

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1082]

**Comment by mishraomp** [comment]
@franTarkenton @conbrad @DerekRoberts  what are your thoughts on this stack for the python backend, please add if I am missing something. I have ignored alembic in favor of flyway migrations.
```
[tool.poetry]
name = "backend-python"
version = "0.1.0"
description = "Starter template for Python backend projects"
authors = ["NRIDS"]
readme = "README.md"
packages = [{ include = "backend_python" }]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.95.1"
uvicorn = "^0.22.0"
sqlalchemy = "^2.0.12"
pydantic = "^1.10.7"
requests = "^2.29.0"
[tool.poetry.dev-dependencies]
prospector = "^1.5.1"
pytest = "^7.3.1"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
[tool.coverage.report]
fail_under = 100
[tool.prospector]
strictness = "veryhigh"
test-warnings = true
doc-warnings = true


```

**Comment by conbrad** [comment]
> what are your thoughts on this stack for the python backend, please add if I am missing something. I have ignored alembic in favor of flyway migrations.

Love it. One thing I'd be interested in is using pants build tool to cache common build steps / tests: https://www.pantsbuild.org/

**Comment by mishraomp** [comment]
> > what are your thoughts on this stack for the python backend, please add if I am missing something. I have ignored alembic in favor of flyway migrations.
> 
> Love it. One thing I'd be interested in is using pants build tool to cache common build steps / tests: https://www.pantsbuild.org/

nice one to try, currently we use Dockerfile-based builds where each layer is cached, food for thoughts @DerekRoberts ?

**Comment by DerekRoberts** [comment]
@mishraomp It sounds promising, but I can't quite wrap my head around it.  Maybe the problem is being primarily a JavaScript dev?  Regardless, if @conbrad thinks it's a good idea I'm interested.

**Comment by conbrad** [comment]
> @mishraomp It sounds promising, but I can't quite wrap my head around it. Maybe the problem is being primarily a JavaScript dev? Regardless, if @conbrad thinks it's a good idea I'm interested.

The documentation is terrible but it:
1. Caches module builds hermetically so you get faster builds
2. Able to detect module changes and only run those respective tests for speeding up test runs

**Comment by conbrad** [comment]
Maybe it would make sense as it's own issue though

**Comment by DerekRoberts** [comment]
@conbrad Cool!  Are you using it in WPS?

**Comment by conbrad** [comment]
Not yet, debugging the setup it in a side branch

**Comment by DerekRoberts** [comment]
I look forward to when that hits.  :)

**Comment by franTarkenton** [comment]
Love it!  Python FTW!  :)  

My one comment would be around the alembic piece.  If you are doing incremental model development, and you are using the [sqlalchemy ORM](https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models) to define your data model then alembic becomes a key piece of technology to autogenerate migrations, ideally never having to author any sql yourself.

**Comment by conbrad** [comment]
> Love it! Python FTW! :)
> 
> My one comment would be around the alembic piece. If you are doing incremental model development, and you are using the [sqlalchemy ORM](https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models) to define your data model then alembic becomes a key piece of technology to autogenerate migrations, ideally never having to author any sql yourself.

I'm also familar with sqlalchemy/alembic, it looks like there's flyway db for migrations here, not sure how it interfaces with sqlalchemy.

**Comment by mishraomp** [comment]
> > Love it! Python FTW! :)
> > My one comment would be around the alembic piece. If you are doing incremental model development, and you are using the [sqlalchemy ORM](https://docs.sqlalchemy.org/en/20/orm/quickstart.html#declare-models) to define your data model then alembic becomes a key piece of technology to autogenerate migrations, ideally never having to author any sql yourself.
> 
> I'm also familar with sqlalchemy/alembic, it looks like there's flyway db for migrations here, not sure how it interfaces with sqlalchemy.

Having a discussion with @franTarkenton  on this topic at this very moment, mainly my idea is, flyway runs in a container within docker-compose and then sqlalchemy orm models are generated out of those database in local system and never manually edited, use repository pattern on those models to query or mutate the state.

**Comment by franTarkenton** [comment]
creating the sqlalchemy model from physical... I've used this tool, its not bad.  https://pypi.org/project/sqlacodegen/

**Comment by conbrad** [comment]
> Alembic is drop-in replacement for flyway for handling automated DB deployments. I believe flyway is a much more generic tool and not tied into a specific language, I recommend moving with flyway. About auto-generating models from the database itself , so that devs dont have to go through the pain of identifying missing relationships, cascades or lazy loading etc.. which can lead to hours of debugging sessions.

Sounds good, I'm onboard if it supports the same features etc. One thing to consider in the deployment template is having migrations run in an init container that the API container depends on, so that migrations are always run before app pod start up.

**Comment by mishraomp** [comment]
> > Alembic is drop-in replacement for flyway for handling automated DB deployments. I believe flyway is a much more generic tool and not tied into a specific language, I recommend moving with flyway. About auto-generating models from the database itself , so that devs dont have to go through the pain of identifying missing relationships, cascades or lazy loading etc.. which can lead to hours of debugging sessions.
> 
> Sounds good, I'm onboard if it supports the same features etc. One thing to consider in the deployment template is having migrations run in an init container that the API container depends on, so that migrations are always run before app pod start up.

we are on this path :) https://github.com/bcgov/quickstart-openshift/pull/1099/files#diff-af0d984641cd848a9bc0c041eb6a17d65cbf9aff782de57de60276b82f63aa71R158
