### ISSUE TITLE
JFrog Artifactory login, push, pull

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#112]
I'm really not a fan of this, but expect other people might be.

**Comment by paulushcgcj** [comment]
Are you talking about JFrog Artifactory? or using Github artifact repository?

**Comment by DerekRoberts** [comment]
> Are you talking about JFrog Artifactory? or using Github artifact repository?

JFrog. Title updated to make that clear!

**Comment by DerekRoberts** [comment]
1Team swapped out the registry in our old builder.  Works great!  Will incorportate into our builder.  Thanks @andrwils!  :)

https://github.com/bcgov-nr/nr-funbucks/blob/main/.github/workflows/build-push-dev-fb-helper-image.yml

**Comment by DerekRoberts** [comment]
Now out of scope.
