### ISSUE TITLE
Env var addition to DC is not reflected

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1191]
**Describe the Bug**
Adding new env var in the DC is not reflected in the pr pipeline.

**Expected Behaviour**
New env vars should show up in the latest deployment.

**Actual Behaviour**
Only existing env vars shows up.

** Steps To Reproduce**
Add a new environment variable in the 2nd run of the pr pipeline when the dc already exist in openshift. NOT in the first run.

**Comment by mishraomp** [comment]
@DerekRoberts looks like I was hallucinating,  it is working as expected, https://console.apps.silver.devops.gov.bc.ca/k8s/ns/32d13a-dev/pods/quickstart-openshift-1182-frontend-38-b5km7/environment

**Comment by DerekRoberts** [comment]
Great news for me, terrible news for you! ;) @mishraomp
