### ISSUE TITLE
add timeouts to the github workflows

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1363]
currently there is no timeouts in place which holds onto runners for long time.

**Comment by DerekRoberts** [comment]
Any opinions on whether this is best done in the actions vs quickstart?  I wouldn't mind the answer being `both`.  @mishraomp

**Comment by mishraomp** [comment]
> Any opinions on whether this is best done in the actions vs quickstart? I wouldn't mind the answer being `both`. @mishraomp

I would vote for actions, with the option to override it :). default value 10 minutes.

**Comment by DerekRoberts** [comment]
https://nesin.io/blog/github-action-timeout
