### ISSUE TITLE
Allow multiple tags for the same image

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1469]
[mishraomp](https://github.com/mishraomp) commented [1 hour ago](https://github.com/bcgov-nr/action-builder-ghcr/issues/35#issue-1930768676)
> Currently one one tag is allowed for the image, it would be better if we allow multiple tags as it is supported natively by the action :)

https://github.com/bcgov-nr/action-builder-ghcr/issues/35

**Comment by mishraomp** [comment]
close, teams can retag in a next step
