### ISSUE TITLE
Add versioning increment for image tags of pr

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1472]
Currently image tags are based on numbers and for the same pr if code is updated and tag is not changed helm wont redeploy to fix this, we will create tags like pr_number.version where version will be auto incremented for each commit.

**Comment by mishraomp** [comment]
same here , add this to helm repo @DerekRoberts

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/quickstart-openshift/issues/1473#issuecomment-1758417293

**Comment by mishraomp** [comment]
Closed as we use digest for helm deplos
