### ISSUE TITLE
Handle Pull Request Closed Scenario when code is not merged.

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1499]
In the current scenario, when a PR is closed, even though the code was not merged, it is running the full workflow and then running the merge workflow causing unnecessary tags and rollouts.

we need to find a way to clean the OpenShift Resources and not do anything further when a PR is closed without code being merged.

**Comment by DerekRoberts** [comment]
This is surprisingly tricky. Let's plan it out Monday. Have a good weekend! :)

**Comment by mishraomp** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#using-data-from-the-triggering-workflow
@DerekRoberts , this is the way :)
