### ISSUE TITLE
bug: look into prod deployment issue, why image tags are not getting passed.

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1521]
https://github.com/bcgov/quickstart-openshift/actions/runs/6635820465/job/18027420724

**Comment by mishraomp** [comment]
missing needs reference
`  deploys-prod:
    name: Deploys (prod)
    needs: [cypress-e2e, integration-tests]`

**Comment by DerekRoberts** [comment]
@mishraomp Thanks!  And done.  :)
