### ISSUE TITLE
PR close workflow not triggered for Auto Close of PR

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1568]
https://github.com/bcgov/quickstart-openshift/pull/1555

**Comment by DerekRoberts** [comment]
Looks like Renovate is renaming PRs and closing in the same step when there's an autoclose.  Thankfully this only seems to be an issue when Renovate users are changed.  I have not been able to figure out how to reproduce this otherwise.  Closing, but will revisit as necessary.
