### ISSUE TITLE
Investigate merge queues

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1603]
Now that the merge process has been revised it might make sense to use merge queues.  Investigate again!

**Comment by DerekRoberts** [comment]
Temporary fork. Will be merged into QS if accepted.

https://github.com/bcgov/quickstart-openshift-mergeQueues

**Comment by DerekRoberts** [comment]
https://github.com/bcgov/quickstart-openshift-mergeQueues/pull/1

**Comment by DerekRoberts** [comment]
`The merge queue ... does not require a pull request author to update their pull request branch and wait for status checks to finish before trying to merge.`

Maybe useful for large projects, but I'm not seeing a use for us.  @mishraomp @cberg-aot ?

**Comment by DerekRoberts** [comment]
Lots of complaints and ugly workarounds here.
https://github.com/orgs/community/discussions/51120

**Comment by mishraomp** [comment]
> `The merge queue ... does not require a pull request author to update their pull request branch and wait for status checks to finish before trying to merge.`
> 
> Maybe useful for large projects, but not really us. @mishraomp? @cberg-aot?

I totally agree,  we dont need merge queues.

**Comment by DerekRoberts** [comment]
Setup ready, but I'm unsure if we'll merge the work.  Please feel free to poke around, especially by sending PRs.

https://github.com/bcgov/quickstart-openshift-merge-queues
