### ISSUE TITLE
Build Triggers

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1716]
Not remembering exact scenario:

2 PRs in progress, 
1st PR got merged, 2nd PR got updated from main, and now the builds are not triggered.

**Comment by DerekRoberts** [comment]
This should be handled one of two ways, depending on how PRs are configured.

Requiring PRs be up to date:
* 2nd PR is merged
* 1st PR becomes stale
* Update 1st, which runs PR workflow
* This replaces any updated containers

Merge Queue:
* 2nd PR is merged, including retags on PR close
* 1st PR hits the merge queue stale
* Merge queue updates against main
* This replaces any updated containers

That said, I'm sure we can poke holes in this process!  @mishraomp Please close this issue when/if you are satisfied.  We can create follow up tickets for anything not covered.
