### ISSUE TITLE
Schedule Helm  clean up is deleting resources outside of scope.

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1755]
Currently, the scheduled job that cleans up helm resources is removing helm installs outside the scope.

provide scope with release name to narrow down the uninstalls.

**Comment by DerekRoberts** [comment]
@mishraomp Outside of scope?  It's should be cleaning up anything a week old.  Please explain?

**Comment by mishraomp** [comment]
namespace can be used for other deployments outside of the repository, and the schedule jobs should not delete that.
for example:
`Quickstart-openshift-*` releases should be deleted but not if someone has `Airflow` or `Airbyte` deployed outside of this workflow.

**Comment by DerekRoberts** [comment]
Resolved by https://github.com/bcgov/quickstart-openshift/pull/1757.
