### ISSUE TITLE
PR description is overriden by Renovate bot

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1772]
Currently renovate generated PR is overriding the PR description added, need a way tp fix this don't know how.
https://github.com/bcgov/quickstart-openshift/pull/1767

![image](https://github.com/bcgov/quickstart-openshift/assets/32200996/f9a92848-7bbe-47df-95df-b7e49c28c14e)

**Comment by DerekRoberts** [comment]
Our descriptions haven't actually been overwritten, they're pushed offscreen.  Expand the pull-down menu at the bottom of Renovate PRs.
