### ISSUE TITLE
Github App for Full  Webhook Control 

### ISSUE THREAD

**Issue by cberg-aot** [bcgov/quickstart-openshift#1811]
**As a** *Developer* **I want** *Github App* **So That** *I have access to additional webooks and integrations*

**Additional Context**

- Catching Gate events requires Github Actions 
- Catching Deploy events & status requires Github Actions
- https://docs.github.com/en/apps/creating-github-apps/writing-code-for-a-github-app/building-a-github-app-that-responds-to-webhook-events

**Acceptance Criteria**

- [ ] Given a PR Deploy, When Gate Occures, Then Event is thrown (gated, success)
- [ ] Given a Deployment (Dev/Test/Prod), When Deployment occures, Then Event is thrown(started,successful)

**Comment by DerekRoberts** [comment]
This is controlled at the org level, so not an option for us.  :'(
