### ISSUE TITLE
feat: backend endpoint verifier

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1840]
Idea via and done in collaboration with @RMCampos:

```
Create a script (bash for example) to parse all backend files (python, java, etc) looking for endpoints and calling them, without authentication, making sure all of them respond with 401 or 403
And put that on QuickStart template, on PR open CI
...
There will be public ones, I know. We could map the public ones somehow.
```

Relevant?  https://github.com/bcgov/nr-spar/tree/main/backend/test/postman

**Comment by mishraomp** [comment]
I would  like to debate this one, we don't need to open backend routes to internet @DerekRoberts

**Comment by DerekRoberts** [comment]
@mishraomp I agree.  We've already decided to route backend traffic through the frontend.
