### ISSUE TITLE
feat: revise Helm chart structure

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#1841]
After consuming this template everybody gets charts in `charts/openshift-quickstart`, which is a little clunky.  I suggest `charts/app` or something similarly generic.

NOTE: This change could cause scripting problems and revisiting previous repos.

**Comment by mishraomp** [comment]
should be done now

**Comment by DerekRoberts** [comment]
Thanks and closing!  @mishraomp
