### ISSUE TITLE
Migrate images from ghcr to Openshift

### ISSUE THREAD

**Issue by cberg-aot** [bcgov/quickstart-openshift#1889]
**Describe the task**
Related to https://github.com/bcgov/quickstart-openshift/issues/1888

Images should be moved away from ghcr to avoid the terrible issues around manifest corruption that we have been experiencing, among other potential issues.  

Move images into Openshift (how? - not as imagestreams)

**Acceptance Criteria**
- [ ] Pipeline automatically moves images into Openshift image registry

**Additional context**
- ![image](https://github.com/bcgov/quickstart-openshift/assets/93226309/01213df7-c345-4029-9ab3-532d34448597)

**Comment by mishraomp** [comment]
if it is very much required, use artifactory as read through cache, which caches your images, not much change you can just update the image registry from `ghcr.io` to `artifacts.developer.gov.bc.ca/github-docker-remote`, again this is only for readonly cache, not pushing to artifactory, so no extra step needed, if you want to cache images.

cc @DerekRoberts

**Comment by DerekRoberts** [comment]
@mishraomp I have some ideas for this.  Ideally we could add imagestreamtags back into select projects to allow local cataloging of images.  It's not going into the quickstart, but could make @cberg-aot 's opressors happy!

**Comment by mishraomp** [comment]
I would rather have pull-through cache than ImageStreams, if using imagestreams for lot of heavy storage platform services team will flag it , come at you for removing imagestream tags

fyi

**Comment by DerekRoberts** [comment]
Good point!  How about we limit this to just PROD?

**Comment by mishraomp** [comment]
> Good point! How about we limit this to just PROD?

Agreed

**Comment by DerekRoberts** [comment]
This has been dismissed for the QS, but still used elsewhere.  Closing!
