### ISSUE TITLE
Need to look at how to avoid ZAP rate limiting issues

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1941]
Thanks to @afwilcox for reporting.
https://github.com/bcgov/nr-compliance-enforcement/actions/runs/8806409114/job/24171796325

Error: You have exceeded a secondary rate limit. Please wait a few minutes before you try again. If you reach out to GitHub Support for help, please include the request ID E0A8:2C1F3A:1299426:1E4A642:662816D6. - https://docs.github.com/free-pro-team@latest/rest/overview/rate-limits-for-the-rest-api#about-secondary-rate-limits

**Comment by mishraomp** [comment]
may be it happens with repository where matrix strategy is used and multiple zap scans for different components are running in parallel, just assumption based on the finding of C&E repo, since that's the only one with 3 components having routes exposed and pen test enabled.

**Comment by mishraomp** [comment]
> @mishraomp I'm unfortunately not sure we can do anything about this. It's a ZAP bug that doesn't appear to be recurring regularly. Should we just keep notes and try to predict fails?

may be it happens with repository where matrix strategy is used and multiple zap scans for different components are running in parallel, just assumption based on the finding of C&E repo, since that's the only one with 3 components having routes exposed and pen test enabled.

**Comment by DerekRoberts** [comment]
ZAP isn't wonderfully configurable, but we could use sequential instead of parallel runs.  Any idea how often the problem happens?

**Comment by DerekRoberts** [comment]
Poop.  This error is turning up elsewhere.
https://github.com/bcgov/quickstart-openshift/actions/runs/8785653950/job/24106670587

**Comment by DerekRoberts** [comment]
I think this has been resolved upstream.  Closing.
