### ISSUE TITLE
Abstract resources to values.yml

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1950]
currently resources are hardcoded in templates, which makes it difficult to set for environment-specific needs. Read from values.yml which can help in providing different resources for different env. PR or TEST, does not need to be same as PROD.

**Comment by DerekRoberts** [comment]
@mishraomp Feedback on Helm has been mixed.  Let's look at how to simplify or at least rearrange.

**Comment by mishraomp** [comment]
> @mishraomp Feedback on Helm has been mixed. Let's look at how to simplify or at least rearrange.

Totally Agree.

K8S/Openshift with GHA is a LOT to learn, and adding HELM on top of it is making it lethal for new teams trying to onboard.

**Comment by DerekRoberts** [comment]
Looks like this is being phased out.  At minimum the priority is down.
