### ISSUE TITLE
Support Node.js version 22

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1966]
Node.js 22 is released as current, lets start exploring to migrate workloads to 22 and see what impacts we are seeing.

**Comment by mishraomp** [comment]
https://nodejs.org/en/blog/announcements/v22-release-announce

**Comment by mishraomp** [comment]
GCR distroless for 22 is also available, https://github.com/GoogleContainerTools/distroless/tree/main/nodejs

**Comment by DerekRoberts** [comment]
@mishraomp Yeah! Let's get this rolling. :D

**Comment by mishraomp** [comment]
> @mishraomp Yeah! Let's get this rolling. :D

lets try pubcode first, the least disruptive ;)

**Comment by DerekRoberts** [comment]
@mishraomp That's the best and the worst case way to put it. :D
https://github.com/bcgov/pubcode/issues/344

**Comment by DerekRoberts** [comment]
Long since done!  Closing.
