### ISSUE TITLE
quarkus updates are not fired by renovate

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#1979]
current version of quarkus is 3.10.2, backend java is at 3.8.2 , not sure why renovate is not firing up updates.

**Comment by DerekRoberts** [comment]
Quarkus updates seem to be going through.  There are failures, but mostly surrounding timeouts, I hope...

https://github.com/bcgov/quickstart-openshift-backends/pull/154/files#diff-d7906adf659e13c4685995c3e95cee665019647a96ef7203be07dfbfb37983fcR15
