### ISSUE TITLE
decision: ghcr cleanup by default?

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#2001]
Right now the builder action does not cleanup old packages by default.  The QuickStart manually specifies cleanup after 50 packages.  Should the builder do the same by default?  How about yes, but with a higher threshold, like 100?

@mishraomp @webgismd @paulushcgcj @cberg-aot

**Comment by mishraomp** [comment]
I am ok with 100, just curious to see if it kicks off, `manifest unknown errors` again

**Comment by DerekRoberts** [comment]
@mishraomp I've been working on catching and rebuilding when `manifest unknown` errors crop up.  We still don't really understand what's causing that, since it's been happening on non-cleanup up packages too.

**Comment by DerekRoberts** [comment]
Long since resolved.
