### ISSUE TITLE
Keep Version failing on fresh repos

### ISSUE THREAD

**Issue by mishraomp** [bcgov/quickstart-openshift#2065]
Error: get versions API failed. Package not found.
https://github.com/bcgov/turl/actions/runs/10648981119/job/29518613841

**Comment by DerekRoberts** [comment]
Sorry, this one came and went before I even got to it!

**Comment by mishraomp** [comment]
can we reopen this, this is still an issue
https://github.com/bcgov/nr-rec-resources/actions/runs/12035485788/job/33554562663

**Comment by DerekRoberts** [comment]
https://github.com/bcgov-nr/action-builder-ghcr/pull/61
