### ISSUE TITLE
Gather variables and populate templates

### ISSUE THREAD

**Issue by gormless87** [bcgov/quickstart-openshift#222]
**As a** *(developer)* **I want** *(to be able to manually deploy FOM to dev)* **So That** *(we can have sandboxed/testing deployments)*

**Additional Context**
- NOT collide with existing deployments
- repeatable so that it can be put into a pipeline

**Acceptance Criteria**
- [ ] Given (task is complete), When (deployment performed), Then (successful deployment)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by DerekRoberts** [comment]
Out of scope.
