### ISSUE TITLE
Define Network Policies

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#249]
Define network policies for communication between containers. Allow specifying which pods can communicate with each other?

- Initialize database passwords 
-Encryption keys (To be decided)  (We could link to another repo as an example)

**Comment by franTarkenton** [comment]
just an example: 
 https://github.com/bcgov/smk-helms/tree/master/charts/smk-init-helm-chart/templates

**Comment by DerekRoberts** [comment]
Include network policies and service accounts.

**Comment by DerekRoberts** [comment]
Required for Team Alliance.

**Comment by DerekRoberts** [comment]
Long since solved by @mishraomp.
