### ISSUE TITLE
DBA-Assist OpenShift Container - Database Investigator

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#291]
Create an OpenShift container based on Postgres that can troubleshoot/inspect production databases.

- Tools: ss, netstat, ps and more
- Database secrets
- Database volumes
- Schema creation tools/docs

**Comment by franTarkenton** [comment]
Thinking this would include two pieces... Possibly a repo with GITHUB actions that builds the container... that way if we need to add more utilities to the container its an easy code edit.

Also thinking this would include some good docs that describe the steps used to:
* create the container
* add new utilities to the container
* how to temporarily spin up the container to assist with openshift debugging.

**Comment by ArogeG** [comment]
Discussion with the database team to clarify requirements and determine the implementation pattern. This should possibly be driven by the database team and a separate repo should probably be created. @DerekRoberts is happy to assist.

**Comment by DerekRoberts** [comment]
Out of scope.
