### ISSUE TITLE
High level vision of Greenfield Template usage

### ISSUE THREAD

**Issue by gormless87** [bcgov/quickstart-openshift#375]
Describe the philosophy of (newly simplified) Greenfield Pipeline Template - what is in scope, what is left generic and open to customization/augmentation by adopting teams.

This sounds a bit like a 'Roadmap'

Define vision and goal of the greenfield template product. 

- create meeting with devops representatives from each of the teams to identify needs and brainstorm
-Groom the backlog
**Audience:** 
DevOps team 
Decide on OpenShift and AWS 
Stakeholders:
- FSA teams 
-Citzs security Team (platform security) -We are using their Namespace
-Database Expert to consult with (based on the work)***

Create roadmap for the pipeline with versions.

OCP, AWS, ...?

Request for contributions 

What is the handover/support model?

**Comment by DerekRoberts** [comment]
Out of scope.
