### ISSUE TITLE
Integrate AWS with the greenfield template

### ISSUE THREAD

**Issue by ArogeG** [bcgov/quickstart-openshift#437]
**As a** *(developer)* **I want** *to  use the greenfield pipeline for AWS computing and configuration* **So That I can deploy applications in a consistent manner. 

**Additional Context**
- Including database patterns
-Terraform for infrastructure deployment
-Lambda
-API
-Front-end 
- Checks can be reused between Openshift and AWS
-Monitoring 

**Acceptance Criteria**
- [ ] Given (Context), When (action carried out), Then (expected outcome)
- [ ] Given (Context), When (action carried out), Then (expected outcome)

**Definition of Done**
- [ ] Ready to Demo in Sprint Review
- [ ] Does what I have made have appropriate test coverage?
- [ ] Documentation and/or scientific documentation exists and can be found
- [ ] Peer Reviewed by 2 people on the team
- [ ] Manual testing of all PRs in Dev and Prod
- [ ] Merged

**Comment by DerekRoberts** [comment]
Handled in https://github.com/bcgov/quickstart-aws-containers.
