### ISSUE TITLE
Distroless?

### ISSUE THREAD

**Issue by DerekRoberts** [bcgov/quickstart-openshift#768]
Look at distroless.  Its main competition is likely Alpine.  Opinions @mishraomp?

https://github.com/GoogleContainerTools/distroless

**Comment by DerekRoberts** [comment]
Very old flyway example.
https://hub.docker.com/r/jycr/flyway-mysql/dockerfile

**Comment by mishraomp** [comment]
I would love to see how much we are gaining in terms of image size, if using distroless :)

**Comment by DerekRoberts** [comment]
We're moving towards Alpine, but should still compare vs Distroless.

**Comment by DerekRoberts** [comment]
Long since done.  Distroless defeated Alpine!
